server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.12:8848
#        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"